prod1 = input().split()
prod2 = input().split()
cod1 = int(prod1[0])
qnt1 = int(prod1[1])
val1 = float(prod1[2])
cod2 = int(prod2[0])
qnt2 = int(prod2[1])
val2 = float(prod2[2])
total = (qnt1 * val1) + (qnt2 * val2)
print("VALOR A PAGAR: R$", format(total, ".2f"))
